env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: always
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]